# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sRCglMd2LNuEEvGT22rW3kuEylvcinO9
"""

import pandas as pd
teacher=pd.DataFrame({
                'FISH':[ 'Qadamova Zulayho' , "Karimov S"  ],
                "Fani":[ "Sun'iy intellekt asoslari" , "Sun'iy intellekt asoslari"  ],
                "Mashg'ulot turi":[ 'amaliy' , "ma'ruza"   ],
                "Kafedrasi":[ "Axborot texnologiyalari" ,  "Axborot texnologiyalari"    ]
})
print(teacher)

teacher.to_excel("660-guruh teacher's.xlsx")